version: '3.8'

services:

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./volumes/data:/data
      - ./volumes/letsencrypt:/etc/letsencrypt

networks:
  proxy:
    driver: bridge